const styles = {
  cardsWapper: {
    display: "flex",
    justifyContent: "space-around",
  },
  cardButtonWrapper: {
    display: "flex",
    justifyContent: "center",
    flexDirection: "column",
    alignItems: "center",
    padding: "9px 13px 10px 13px",
    marginBottom: "138px",
  },
  topButton: {
    width: "106px",
    height: " 34px",
    left: "207px",
    top: "1218px",
    borderRadius: "8px",
    fontSize: "12px",
    fontFamily: "Quicksand",
    color: "white",
    marginBottom: "10px",
    fontFamily: "Quicksand",
    fontStyle: "normal",
    fontWeight: "700",
    fontSize: "12px",
    lineHeight: "15px",
  },
  card: {
    width: " 369px",
    height: "461px",
    display: "flex",
    padding: "30px",
    boxShadow: "0px 4px 4px rgba(0, 0, 0, 0.25)",
    background: "#EFEFEF",
  },
  spanBorder: {
    border: "none",
    borderRadius: "5px",
    width: "106px",
    height: " 34px",
    left: "207px",
    top: "1218px",
    borderRadius: "8px",
    fontSize: "12px",
    fontFamily: "Quicksand",
    color: "white",
    marginBottom: "10px",
    fontFamily: "Quicksand",
    fontStyle: "normal",
    fontWeight: "700",
    fontSize: "12px",
    lineHeight: "34px",
    textAlign: "center",
  },
  h5: {
    fontWeight: "500",
    fontFamily: "Quicksand",
  },
  cardButton: {
    border: "1px solid #157599",
    backgroundColor: "white",
    color: "#157599",
    fontFamily: "Quicksand",
    fontWeight: 700,
  },
  cardBody: {
    paddingLeft: 0,
  },
};

export default styles;
