const styles = {
  container: {
    background: "#157599",
    top: "3984px",
    maxHeight: "579px",
    padding: "180.12px 58px",
    display: "flex",
  },
  itemContainer: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  description: {
    fontFamily: "Roboto",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "25px",
    margin: "36px 122.76px 50px 0",
    color: "#FFFFFF",
  },
  leftSection: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    marginLeft: "181.13px",
  },
  sosmed: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    left: "183.94px",
    bottom: "113px",
    width: "214px",
    height: "30px",
  },
  centerSection: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-center",
    padding: "85px 0",
    marginLeft: "122.76px",
  },
  navigasi: {
    marginBottom: "36px",
    marginTop: "52px",
    fontFamily: "Roboto",
    fontStyle: "normal",
    fontWeight: 900,
    fontSize: "30px",
    lineHeight: "35px",
    color: "#FFFFFF",
  },
  menu: {
    fontFamily: "Roboto",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "20px",
    lineHeight: "23px",
    color: "#a6cbd8",
    marginTop: "27px",
    textDecoration: "none",
    flex: 1,
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-around",
  },
  menuHome: {
    fontFamily: "Roboto",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "20px",
    lineHeight: "23px",
    color: "#FFFFFF",
    textDecoration: "Underline",
  },
  righSection: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    padding: "85px 0",
    marginRight: "375.33px",
  },
  kontak: {
    marginTop: "159px",
    marginBottom: "36px",
    fontFamily: "Roboto",
    fontStyle: "normal",
    fontWeight: "900",
    fontSize: "30px",
    lineHeight: "35px",
    color: "#FFFFFF",
  },
  kontakSection: {
    flex: 1,
    display: "flex",
    flexDirection: "row",
  },
  locationIcon: {
    width: "16.6px",
    height: "21px",
    marginBottom: "58px",
  },
  locationText: {
    marginLeft: "17px",
    marginBottom: "18px",

    fontFamily: "Roboto",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "18px",
    lineHeight: "21px",
    color: "#FFFFFF",
  },
  whatsAppIcon: {
    width: "19.37px",
    height: "19.2px",
  },
  whatsAppNumber: {
    marginLeft: "17px",
    marginBottom: "18px",
    fontFamily: "Roboto",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "18px",
    lineHeight: "21px",
    color: "#FFFFFF",
  },
  emailIcon: {
    width: "20.13px",
    height: "16px",
  },
  emailText: {
    marginLeft: "17px",
    marginBottom: "188px",

    fontFamily: "Roboto",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "18px",
    lineHeight: "21px",
    color: "#FFFFFF",
  },
};

export default styles;
