const styles = {
  container: {
    flexDirection: "column",
    backgroundColor: "white",
    width: "80%",
    flex: 1,
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-start",
    padding: "75px",
    boxSizing: "border-box",
  },
  container2: {
    backgroundColor: "#157599",
    width: "100%",
    flex: 1,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // padding: "169px",
  },
  container3: {
    backgroundColor: "#2093BE",
    width: "100%",
    flex: 1,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // padding: "169px",
  },
  container4: {
    backgroundColor: "#2EB3E5",
    width: "100%",
    flex: 1,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // padding: "169px",
  },
  image: {
    zIndex: 3,
  },
  title: {
    fontFamily: "Quicksand",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "30px",
    lineHeight: "38px",
    width: "327px",
    height: "38px",
    left: "70px",
    top: "809px",
    marginBottom: "15px",
  },
  subTitle: {
    fontFamily: "Quicksand",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "30px",
    lineHeight: "25px",
  },
  text: {
    fontFamily: "Quicksand",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "25px",
    lineHeight: "25px",
    color: "white",
    marginTop: "50px",
  },
  border: {
    border: " solid 2px white",
    borderRadius: "50px",
    width: "100px",
    height: "100px",
    backgroundColor: "rgba(255, 255, 255, 0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1,
  },
};

export default styles;
